packages:
  - lib/*
  - web/*
  - app/*
  - .config

catalog:
  '@js-temporal/polyfill': 0.4.4
  '@types/node': 22.18.6
  '@types/react': 19.1.10
  '@types/react-dom': 19.1.7
  '@vitejs/plugin-react': 5.0.0
  '@vitest/browser': 3.2.4
  react: 19.1.1
  react-dom: 19.1.1
  typescript: 5.8.3
  vite: 7.1.2
  vitest: 3.2.4

catalogs:
  playwright:
    '@axe-core/playwright': 4.10.2
    '@playwright/experimental-ct-react': 1.55.0
    '@playwright/test': 1.55.0
    playwright: 1.55.0

onlyBuiltDependencies:
  - esbuild
